name: 2ndCI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: pwdしてみる
      run: pwd
    - name: ls -alしてみる
      run: ls -al
    - name: whoamiしてみる
      run: whoami
    - name: apt-get updateできるか?
      run: sudo apt-get update || echo "だめです"
    - name: apt-get install hogehogeは可能か?
      run: sudo apt-get install -y tree || echo "だめです"
